name: Gitpod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker Image
      run: docker pull gitpod/workspace-full:latest

    - name: Save Docker Image as tar
      run: docker save -o gitpod-workspace-full.tar gitpod/workspace-full:latest

    - name: Compress with 7zip
      run: 7z a gitpod-workspace-full.tar.7z gitpod-workspace-full.tar

    - name: Upload Docker Image
      uses: actions/upload-artifact@v2
      with:
        name: docker-image
        path: gitpod-workspace-full.tar.7z

    - name: Upload to OneDrive
      uses: jakejarvis/onedrive-upload@v1
      with:
        local_path: ./gitpod-workspace-full.tar.7z
        remote_path: /Data
        client_id: ${{ secrets.ONEDRIVE_CLIENT_ID }}
        client_secret: ${{ secrets.ONEDRIVE_CLIENT_SECRET }}
        refresh_token: ${{ secrets.ONEDRIVE_REFRESH_TOKEN }}
